apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: 
        - "sleep" 
        - "600"
    volumeMounts:
    - name: dc1-storage
      mountPath: /tmp/volume
  volumes:
  - name: dc1-storage
    persistentVolumeClaim:
      claimName: pvc-example
