apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apigee-hybrid-mregion
spec:
  generators:
  - list:
      elements:
      - cluster: argocd-1103
        url: https://kubernetes.default.svc
      - cluster: argocd2-1103
        url: https://34.27.240.10
  template:
    metadata:
      name: '{{cluster}}-apigeehybrid'
    spec:
      project: default
      source:
        repoURL: git@github.com:AyoSal/argocd-hybrid-multiregion.git
        targetRevision: HEAD
        path: apps
      destination:
        server: '{{url}}'
        namespace: apigee
