apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apigeehybrid-mregion
  namespace: argocd  
spec:
  generators:
  - clusters: argocd2-1103
    url: https://34.27.240.10
      selector:
        matchLabels:
          app: apigeehybrid
  template:
    metadata:
      name: apigeedc2
    spec:  
      project: default
      source:
        repoURL: git@github.com:AyoSal/argocd-hybrid-multiregion.git
        targetRevision: HEAD  
        path: apps2 
      destination:
        server: '{{url}}'
        namespace: apigee
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
        - CreateNamespace=true  
