apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apigeehybrid-mregion
  namespace: argocd  
spec:
  generators:
  - list: 
      elements:
      - cluster: argocd-1103
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: apigeedc1
    spec:  
      project: default
      source:
        repoURL: git@github.com:AyoSal/argocd-hybrid-multiregion.git
        targetRevision: HEAD  
        path: dc1-app 
      destination:
        server: '{{url}}'
        namespace: apigee
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
        - CreateNamespace=true  
