apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apigeedc1
  namespace: argocd
  annotations:
   notifications.argoproj.io/subscribe.on-deployed.slack: hybridupdates  #Slack Channel name  
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:AyoSal/argocd-hybrid-multiregion.git
    targetRevision: HEAD
    path: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: apigee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
