apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dc1-postsync-job
  namespace: argocd  
spec:
  generators:
  - clusters:
    selector:
      matchLabels:
        name: argo1-cluster
  template:
    metadata:
      annotations:
        argoproj.argoproj.io/sync-wave: "1"
    spec:
      project: default
      source:
        repoURL: git@github.com:AyoSal/argocd-hybrid-multiregion.git
        targetRevision: HEAD
        path: pre-sync-tasks/templates/dc1-postsync
      destination:
        name: https://kubernetes.default.svc
        namespace: argocd 
