apiVersion: batch/v1
kind: Job
metadata:
  name: all-dc-pre-sync-script
spec:
  template:
    spec:
      containers:
      - name: helm-kubectl
        image: ashwinknaik/apigee-ansible-accelrator:v1
        args: [ "/bin/sh", "/tmp/scripts/dc2_pre_sync_script.sh"]
        volumeMounts:
          - name: dc1-storage
            mountPath: /tmp/volume
          - name: config-volume
            mountPath: /tmp/scripts
          - name: kube-config-volume
            mountPath: /root/.kube
      restartPolicy: Never
      volumes:
      - name: dc1-storage
        persistentVolumeClaim:
          claimName: multi-region-pvc
      - name: config-volume
        configMap:
          name:  apigee-hybrid-argo-hook-scripts
      - name: kube-config-volume
        configMap:
          name:  apigee-hybrid-argo-hook-scripts-tmp
  backoffLimit: 2
